### ISSUE TITLE
Cannot get it running in Ubuntu 17.04

### ISSUE THREAD

**Issue by WebfinityDesign** [autominer/autominer#6]
I was looking for something like this and I'm happy I found it, but I cannot get it running on Ubuntu 17.04.
I get this error:

> 2017/11/29 23:17:06 Loaded configuration from "config.yml"
> 2017/11/29 23:17:06 1 coins to mine: TZC
> fatal error: unexpected signal during runtime execution
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]
> 
> runtime stack:
> runtime.throw(0x88e358, 0x2a)
> 	/usr/lib64/golang/src/runtime/panic.go:596 +0x95
> runtime.sigpanic()
> 	/usr/lib64/golang/src/runtime/signal_unix.go:274 +0x2db
> 
> goroutine 11 [syscall, locked to thread]:
> runtime.cgocall(0x7067e0, 0xc420031dd8, 0x88dbbb)
> 	/usr/lib64/golang/src/runtime/cgocall.go:131 +0xe2 fp=0xc420031d98 sp=0xc420031d58
> net._C2func_getaddrinfo(0x7f08e00008c0, 0x0, 0xc420108bd0, 0xc42000e208, 0x0, 0x0, 0x0)
> 	net/_obj/_cgo_gotypes.go:86 +0x68 fp=0xc420031dd8 sp=0xc420031d98
> net.cgoLookupIPCNAME.func2(0x7f08e00008c0, 0x0, 0xc420108bd0, 0xc42000e208, 0xc4200fb120, 0xe, 0x0)
> 	/usr/lib64/golang/src/net/cgo_unix.go:151 +0x171 fp=0xc420031e38 sp=0xc420031dd8
> net.cgoLookupIPCNAME(0xc4200fb120, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
> 	/usr/lib64/golang/src/net/cgo_unix.go:151 +0x1bd fp=0xc420031f38 sp=0xc420031e38
> net.cgoIPLookup(0xc420073140, 0xc4200fb120, 0xe)
> 	/usr/lib64/golang/src/net/cgo_unix.go:203 +0x4d fp=0xc420031fc8 sp=0xc420031f38
> runtime.goexit()
> 	/usr/lib64/golang/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420031fd0 sp=0xc420031fc8
> created by net.cgoLookupIP
> 	/usr/lib64/golang/src/net/cgo_unix.go:213 +0xb4
> 
> goroutine 1 [select]:
> net/http.(*Transport).getConn(0xc3ab20, 0xc4200fb100, 0x0, 0xc420015800, 0x4, 0xc4200fb120, 0x11, 0x0, 0x0, 0x3173000000001017)
> 	/usr/lib64/golang/src/net/http/transport.go:913 +0xb92
> net/http.(*Transport).RoundTrip(0xc3ab20, 0xc42000ae00, 0xc3ab20, 0x0, 0x0)
> 	/usr/lib64/golang/src/net/http/transport.go:378 +0x58c
> net/http.send(0xc42000ae00, 0xc40e40, 0xc3ab20, 0x0, 0x0, 0x0, 0x0, 0x8, 0xc42000e1d8, 0x40fd78)
> 	/usr/lib64/golang/src/net/http/client.go:249 +0x162
> net/http.(*Client).send(0xc69ea0, 0xc42000ae00, 0x0, 0x0, 0x0, 0xc42000e1d8, 0x0, 0x1, 0xc420108600)
> 	/usr/lib64/golang/src/net/http/client.go:173 +0x108
> net/http.(*Client).Do(0xc69ea0, 0xc42000ae00, 0xc420015800, 0x585, 0x0)
> 	/usr/lib64/golang/src/net/http/client.go:595 +0x254
> net/http.(*Client).Get(0xc69ea0, 0xc420015800, 0x585, 0x585, 0xc420015800, 0xc4200c8000)
> 	/usr/lib64/golang/src/net/http/client.go:393 +0xa7
> net/http.Get(0xc420015800, 0x585, 0xc420051a20, 0x2, 0x2)
> 	/usr/lib64/golang/src/net/http/client.go:367 +0x41
> main.UpdateCoins(0xc420018b40, 0x0, 0x0)
> 	/opt/autominer/net.go:18 +0x155
> main.updateAndMine()
> 	/opt/autominer/main.go:151 +0x58
> main.main()
> 	/opt/autominer/main.go:98 +0x500
> 
> goroutine 17 [syscall, locked to thread]:
> runtime.goexit()
> 	/usr/lib64/golang/src/runtime/asm_amd64.s:2197 +0x1
> 
> goroutine 5 [syscall]:
> os/signal.signal_recv(0x0)
> 	/usr/lib64/golang/src/runtime/sigqueue.go:116 +0x104
> os/signal.loop()
> 	/usr/lib64/golang/src/os/signal/signal_unix.go:22 +0x22
> created by os/signal.init.1
> 	/usr/lib64/golang/src/os/signal/signal_unix.go:28 +0x41
> 
> goroutine 6 [select, locked to thread]:
> runtime.gopark(0x895530, 0x0, 0x880536, 0x6, 0x18, 0x2)
> 	/usr/lib64/golang/src/runtime/proc.go:271 +0x13a
> runtime.selectgoImpl(0xc42003cf50, 0x0, 0x18)
> 	/usr/lib64/golang/src/runtime/select.go:423 +0x1364
> runtime.selectgo(0xc42003cf50)
> 	/usr/lib64/golang/src/runtime/select.go:238 +0x1c
> runtime.ensureSigM.func1()
> 	/usr/lib64/golang/src/runtime/signal_unix.go:434 +0x2dd
> runtime.goexit()
> 	/usr/lib64/golang/src/runtime/asm_amd64.s:2197 +0x1
> 
> goroutine 7 [chan receive]:
> main.main.func1(0xc420072b40)
> 	/opt/autominer/main.go:87 +0x44
> created by main.main
> 	/opt/autominer/main.go:95 +0x4c8
> 
> goroutine 8 [select]:
> net.(*Resolver).LookupIPAddr(0xc8ce04, 0xc45800, 0xc420073080, 0xc4200fb120, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0)
> 	/usr/lib64/golang/src/net/lookup.go:165 +0x9b1
> net.(*Resolver).internetAddrList(0xc8ce04, 0xc45800, 0xc420073080, 0x87fb08, 0x3, 0xc4200fb120, 0x11, 0x0, 0x0, 0xc4200417e8, ...)
> 	/usr/lib64/golang/src/net/ipsock.go:245 +0x4cc
> net.(*Resolver).resolveAddrList(0xc8ce04, 0xc45800, 0xc420073080, 0x87fd72, 0x4, 0x87fb08, 0x3, 0xc4200fb120, 0x11, 0x0, ...)
> 	/usr/lib64/golang/src/net/dial.go:188 +0x6b3
> net.(*Dialer).DialContext(0xc420072600, 0xc457c0, 0xc420010268, 0x87fb08, 0x3, 0xc4200fb120, 0x11, 0x0, 0x0, 0x0, ...)
> 	/usr/lib64/golang/src/net/dial.go:349 +0x247
> net.(*Dialer).DialContext-fm(0xc457c0, 0xc420010268, 0x87fb08, 0x3, 0xc4200fb120, 0x11, 0xc420041a60, 0x69ad9d, 0xc420010268, 0x821ce0)
> 	/usr/lib64/golang/src/net/http/transport.go:45 +0x73
> net/http.(*Transport).dial(0xc3ab20, 0xc457c0, 0xc420010268, 0x87fb08, 0x3, 0xc4200fb120, 0x11, 0x0, 0x0, 0x0, ...)
> 	/usr/lib64/golang/src/net/http/transport.go:849 +0x227
> net/http.(*Transport).dialConn(0xc3ab20, 0xc457c0, 0xc420010268, 0x0, 0xc420015800, 0x4, 0xc4200fb120, 0x11, 0x0, 0x0, ...)
> 	/usr/lib64/golang/src/net/http/transport.go:1008 +0x1c4c
> net/http.(*Transport).getConn.func4(0xc3ab20, 0xc457c0, 0xc420010268, 0xc420108720, 0xc420072d20)
> 	/usr/lib64/golang/src/net/http/transport.go:908 +0x78
> created by net/http.(*Transport).getConn
> 	/usr/lib64/golang/src/net/http/transport.go:910 +0x3a3
> 
> goroutine 10 [select]:
> net.cgoLookupIP(0xc45800, 0xc420073080, 0xc4200fb120, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
> 	/usr/lib64/golang/src/net/cgo_unix.go:214 +0x2f5
> net.(*Resolver).lookupIP(0xc8ce04, 0xc45800, 0xc420073080, 0xc4200fb120, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0)
> 	/usr/lib64/golang/src/net/lookup_unix.go:69 +0x125
> net.(*Resolver).(net.lookupIP)-fm(0xc45800, 0xc420073080, 0xc4200fb120, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0)
> 	/usr/lib64/golang/src/net/lookup.go:156 +0x56
> net.glob..func11(0xc45800, 0xc420073080, 0xc420011ca0, 0xc4200fb120, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0)
> 	/usr/lib64/golang/src/net/hook.go:19 +0x52
> net.(*Resolver).LookupIPAddr.func1(0x0, 0x0, 0x0, 0x0)
> 	/usr/lib64/golang/src/net/lookup.go:162 +0x5c
> internal/singleflight.(*Group).doCall(0xc69330, 0xc42001cb90, 0xc4200fb120, 0xe, 0xc420108840)
> 	/usr/lib64/golang/src/internal/singleflight/singleflight.go:93 +0x3c
> created by internal/singleflight.(*Group).DoChan
> 	/usr/lib64/golang/src/internal/singleflight/singleflight.go:86 +0x323

**Comment by autominer** [comment]
Hi, I'm not able to reproduce this in my 17.04 VM. Could you tell me a bit more about your setup, and make sure all packages are up to date?

**Comment by WebfinityDesign** [comment]
I'm running Ubuntu desktop 17.04 64-bit
What are the needed packages?
